config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, :users, only: [:new, :index, :show, :edit]
  post 'users' => 'users#create'
  post 'books' => 'books#create'
  post 'users/:id' => 'users#create'
  post 'books/:id' => 'books#create'
  patch 'books/:id' => 'books#update'
  patch 'users/:id' => 'users#update'
  root to: "homes#top"
  get 'home/about'=>'homes#about'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true,
    length: { maximum: 200 }
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  def image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
  validates :name, uniqueness: true,
    length: { minimum: 2, maximum: 20 }
  validates :introduction,
    length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?
    
  def sign_up
    flash[:notice] = "Welcome! You have signed up successfully."
  end
  
  def signed_in
    flash[:notice] = "Signed in successfully."
  end
  
  def sign_aut
    flash[:notice] = "Signed out successfully."
  end
  
  def
    after_sign_in_path_for(resource)
    user_path(current_user)
  end
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     redirect_to book_path(@book.id),notice: "You have created book successfully."
    else
     render :index
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @user = current_user
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(params[:id]),notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:id, :title, :body, :email, :user_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user),notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:id, :name, :email, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h1>Editing Book</h1>
          <% if @book.errors.any? %>
  　        <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    　　      <% @book.errors.full_messages.each do |message| %>
    　　        <li><%= message %></li>
    　　      <% end %>
　        <% end %>
  		  <%= form_with model: @book, method: :patch do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class: "form-control book_title", id: "book_title" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class: "form-control book_body", id: "book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Update Book', class: "btn btn-success" %>
          </div>
        <% end %>
  		  <%= link_to "Show",book_path(@book.id) %> | <%= link_to "Back",books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<body>
  <main>
    <p id="notice"></p>
    <div class="container px-5 px-sm-0">
        <% if @book.errors.any? %>
  　       <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    　　        <% @book.errors.full_messages.each do |message| %>
     　          <li><%= message %></li>
    　　      　<% end %>
　      <% end %>
      <div class="row">
        <div class="col-md-3">
          <h2>User info</h2>
            <%= image_tag @user.image %>
          <table class="table">
            <tbody>
              <tr></tr>
              <tr>
                <th>name</th>
                <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
              </tr>
            </tbody>
          </table>
          <div class="row">
            <%= link_to edit_user_path(@user),class: "btn btn-outline-secondary btn-block edit_user_id" do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          </div>
          <h2 class="mt-3">New book</h2>
          <%= form_with model: @book, method: :post do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class: "form-control book_title", id: "book_title" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class: "form-control book_body", id: "book_body"  %>
            </div>
            <div class="form-group">
              <%= f.submit 'Create Book', class: "btn btn-success" %>
            </div>
          <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%=link_to user_path(book.user_id) do %>
                    <%= image_tag book.user.image %>
                  <% end %>
                </td>
                <td>
                  <%=link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </main>
</body>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<body>
  <%= flash[:notice] %>
  <main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <h2>User info</h2>
            <%= image_tag @user.image %>
          <table class="table">
            <tbody>
              <tr></tr>
              <tr>
                <th>name</th>
                <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
              </tr>
            </tbody>
          </table>
          <div class="row">
            <%= link_to edit_user_path(@user),class: "btn btn-outline-secondary btn-block edit_user_id" do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          </div>
          <h2 class="mt-3">New book</h2>
          <%= form_with model: @book, method: :post do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class: "form-control book_title", id: "book_title" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class: "form-control book_body", id: "book_body"  %>
            </div>
            <div class="form-group">
              <%= f.submit 'Create Book', class: "btn btn-success" %>
            </div>
          <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
          <table class="table">
            <tbody>
              <tr>
                <td>
                  <%=link_to user_path(@user.id) do %>
                    <%= image_tag @user.image %>
                    <br>
                    <%= @user.name %>
                  <% end %>
                </td>
                <td>
                  <%=link_to book_path(@books.id) do %>
                    <%= @books.title %>
                  <% end %>
                </td>
                <td>
                  <%= @books.body %>
                </td>
                <% if @books.user == current_user %>
                  <td>
                    <%= link_to "Edit",edit_book_path(@books.id),class: "btn btn-sm btn-success" %>
                  </td>
                  <td>
                    <%= link_to "Destroy", destroy_book_path(@books.id),class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
                  </td>
                <% end %>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </main>
</body>

app/views/homes/about.html.erb
<body>
  <main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <h1 class="px-3 mx-auto">
          Welcome to
          <i class="fas fa-book"></i><strong>Bookers</strong>!
        </h1>
      </div>
    </div>
  </main>
</body>

app/views/homes/top.html.erb
<body>
  <%= flash[:notice] %>
  <main>
    <div class="container">
      <div class="row">
        <div class="mx-auto col-ll col-sm-10 col-lg-8 col-xl-6">
          <h1>
            welcome to
            <i class="fas fa-book"></i><strong>Bookers</strong>
            !!
          </h1>
          <p>
            In
            <i class="fas fa-book"></i><strong>Bookers</strong>,
          </p>
          <p>
            you can share and exchange your opinions , inpressions , and emotions
          </p>
          <p>about various books!</p>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
            </div>
            <div class="row">
              <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
            <a class="navbar-brand" href="/">
              <span>Bookers</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li>
                  <%= link_to user_path(current_user),class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path,class: "nav-link text-light" do %>
                    <i class="fas fa-users"></i>
                    Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path,class: "nav-link text-light" do %>
                    <i class="fas fa-book-open"></i>
                    Books
                  <% end %>
                </li>
                <li>
                  <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
                    <i class="fas fa-sign-out-alt"></i>
                    Log out
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <% else %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
            <a class="navbar-brand" href="/">
              <span>Bookers</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li>
                  <%= link_to root_path,class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to home_about_path,class: "nav-link text-light" do %>
                    <i class="fas fa-link"></i>
                    About
                  <% end %>
                </li>
                <li>
                  <a class="nav-link text-light" href="/users/sign_up">
                    <i class="fas fa-user-plus"></i>
                    Sign up
                  </a>
                </li>
                <li>
                  <a class="nav-link text-light" href="/users/sign_in">
                    <i class="fas fa-sign-in-alt"></i>
                    Log in
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <% end %>
    <%= yield %>
      <footer>
        <div class="container mt-5">
          <div class="row">
           <div class="mx-auto">
             <p>CopyRight Infratop.inc</p>
           </div>
          </diva>
        </div>
      </footer>
  </body>

</html>

app/views/users/edit.html.erb
<body>
  <main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h2>User info</h2>
          <div>
            <% if @user.errors.any? %>
  　           <h3><%=@user.errors.count %>errors prohibited this obj from being saved:</h3>
    　　          <% @user.errors.full_messages.each do |message| %>
     　            <li><%= message %></li>
    　　        　<% end %>
　          <% end %>
　        </div>
          <%= form_with model: @user, method: :patch do |f| %>
            <div class="form-group">
              <label for="user_name">Name</label>
              <%= f.text_field :name, class: "form-control name", id: "user_name" %>
            </div>
            <div class="form-group">
              <label for="user_image">Image</label>
              <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file user_image", id: "user_profile_image" %>
            </div>
            <div class="form-group">
              <label for="user_introduction">Introduction</label>
              <%= f.text_area :introduction, class: "form-control introduction", id: "user_introduction" %>
            </div>
            <div class="form-group">
              <%= f.submit 'Update User', class: "btn btn-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </main>
</body>

app/views/users/index.html.erb
<body>
  <main>
    <p id="notice"></p>
    <div class="container px-5 px-sm-0">
      <div class="row">
        <div class="col-md-3">
          <h2>User info</h2>
             <%= image_tag @user.image %>
          <table class="table">
            <tbody>
              <tr></tr>
              <tr>
                <th>name</th>
                <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
              </tr>
            </tbody>
          </table>
          <div class="row">
            <%= link_to edit_user_path(@user),class: "btn btn-outline-secondary btn-block edit_user_id" do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          </div>
          <h2 class="mt-3">New book</h2>
          <%= form_with model: @book, method: :post do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class: "form-control book_title", id: "book_title" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class: "form-control book_body", id: "book_body"  %>
            </div>
            <div class="form-group">
              <%= f.submit 'Create Book', class: "btn btn-success" %>
            </div>
          <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                   <%= image_tag user.image %>
                </td>
                <td>
                    <%= user.name %>
                </td>
                <td>
                  <%= link_to "Show",user_path(user.id) %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </main>
</body>

app/views/users/show.html.erb
<body>
  <%= flash[:notice] %>
  <main>
    <p id="notice"></p>
    <div class="container px-5 px-sm-0">
      <div class="row">
        <div class="col-md-3">
          <h2>User info</h2>
           <%= image_tag @user.image %>
          <table class="table">
            <tbody>
              <tr></tr>
              <tr>
                <th>name</th>
                <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
              </tr>
            </tbody>
          </table>
          <div class="row">
            <%= link_to edit_user_path(@user),class: "btn btn-outline-secondary btn-block edit_user_id" do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          </div>
          <h2 class="mt-3">New book</h2>
          <%= form_with model: @book, method: :post do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class: "form-control book_title", id: "book_title" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class: "form-control book_body", id: "book_body"  %>
            </div>
            <div class="form-group">
              <%= f.submit 'Create Book', class: "btn btn-success" %>
            </div>
          <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%=link_to user_path(@user) do %>
                     <%= image_tag @user.image %>
                  <% end %>
                </td>
                <td>
                  <%=link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </main>
</body>